import { test, expect } from '@playwright/test';

test('test', async ({ page }) => {
  await page.goto('http://localhost:3000/todos');
  await page.getByRole('main').click();
  await page.getByRole('link', { name: '월 19일' }).click();
  await page.getByRole('link', { name: '월 20일' }).click();
  await page.getByRole('link', { name: '월 18일' }).click();
  await page.getByRole('link', { name: 'Todo 추가' }).click();
  await page.getByRole('textbox', { name: '할 일' }).fill('dk');
  await page.getByRole('textbox', { name: '할 일' }).click();
  await page.getByRole('textbox', { name: '할 일' }).fill('알바');
  await page.getByRole('button', { name: '저장' }).click();
  await page.getByText('알바수정삭제').click();
  await page.getByRole('button', { name: '완료 상태 변경' }).click();
  await page.getByRole('link', { name: '이전 주' }).click();
  await page.getByText('월80화90수100목111금120토130일').click();
  await page.getByRole('link', { name: '다음 주' }).click();
  await page.getByRole('link', { name: '월 16일' }).click();
  await page.getByRole('link', { name: 'Todo 추가' }).click();
  await page.getByRole('textbox', { name: '할 일' }).fill('친구 만나기');
  await page.getByRole('button', { name: '저장' }).click();
  await page.getByRole('link', { name: '월 19일' }).click();
  await page.getByRole('button', { name: '삭제' }).nth(1).click();
  await page.getByRole('button', { name: '삭제' }).nth(1).click();
  await page.getByRole('button', { name: '삭제' }).nth(1).click();
  await page.getByRole('link', { name: '진행 중' }).click();
  await page.getByRole('link', { name: '전체' }).click();
  await page.getByText('새 할 일입니다수정삭제').click();
  await page.getByRole('listitem').filter({ hasText: '새 할 일입니다수정삭제' }).getByLabel('완료 상태 변경').click();
  await page.getByRole('link', { name: '완료' }).click();
  await page.getByRole('link', { name: '진행 중' }).click();
  await page.getByRole('link', { name: '전체' }).click();
  await page.getByRole('textbox', { name: '검색할 Todo를 입력하세요' }).click();
  await page.getByRole('textbox', { name: '검색할 Todo를 입력하세요' }).fill('할');
  await page.getByRole('button', { name: '검색' }).click();
  await page.getByRole('link', { name: '진행 중' }).click();
  await page.getByRole('link', { name: '완료' }).click();
  await page.getByRole('link', { name: '전체' }).click();
  await page.getByRole('link', { name: '월 18일' }).click();
  await page.getByRole('link', { name: '월 19일' }).click();
  await page.getByRole('link', { name: '월 18일' }).click();
  await page.getByRole('link', { name: '월 17일' }).click();
  await page.getByRole('button', { name: '삭제' }).nth(1).click();
  await page.getByRole('button', { name: '삭제' }).nth(1).click();
  await page.getByRole('link', { name: '월 19일' }).click();
  await page.getByRole('button', { name: '검색' }).click();
  await page.getByRole('textbox', { name: '검색할 Todo를 입력하세요' }).click();
  await page.getByRole('link', { name: 'Todo 추가' }).click();
  await page.getByRole('textbox', { name: '할 일' }).fill('오류가 있나요');
  await page.getByRole('button', { name: '저장' }).click();
  await page.getByRole('button', { name: '검색' }).click();
  await page.getByRole('textbox', { name: '검색할 Todo를 입력하세요' }).click();
  await page.getByRole('main').click();
  await page.getByRole('textbox', { name: '검색할 Todo를 입력하세요' }).click();
  await page.getByRole('textbox', { name: '검색할 Todo를 입력하세요' }).fill('오류');
  await page.getByRole('button', { name: '검색' }).click();
  await page.getByRole('button', { name: '초기화' }).click();
  await page.getByRole('link', { name: 'Todo 추가' }).click();
  await page.getByRole('button', { name: '저장' }).click();
  await page.getByRole('link', { name: '목록으로 돌아가기' }).click();
  await page.getByRole('link', { name: '수정' }).first().click();
  await page.getByRole('textbox', { name: '할 일 수정' }).fill('오류가 있으면 안됨');
  await page.getByRole('button', { name: '저장' }).click();
  await page.getByRole('link', { name: '다음 주' }).click();
  await page.getByRole('link', { name: '다음 주' }).click();
  await page.getByRole('link', { name: '이전 주' }).click();
  await page.getByRole('link', { name: '월 25일' }).click();
  await page.getByRole('button', { name: '삭제' }).click();
  await page.getByRole('link', { name: '진행 중' }).click();
  await page.getByRole('link', { name: '완료' }).click();
});